#! /bin/bash

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"		# Where this script lives

. $THIS_DIR/config.sh

INT_PID_FILE=$RUN_DIR/int.pid

# make sure our environment exists
mkdir -p $RUN_DIR

if [ ! -d $RUN_DIR ]
then
	echo "The run dir $RUN_DIR does not exist and can't be made. Might want to check permissions or something."
	exit 1
fi

mkdir -p $DATA_DIR

if [ ! -d $DATA_DIR ]
then
	echo "The data dir $DATA_DIR does not exist and can't be made. Might want to check permissions or something."
	exit 2
fi

do_start() {
	
	hcitool lescan --duplicates 2>&1 > /dev/null &
	# get pid
	hcidump -t --raw | grep -C 1 "00 02 15 A4 95" | grep --invert-match '\-\-' | sed "N ;s/\n//; N; s/\n//"| tr '\-:' '  ' | sed "s/\.[0-9][0-9][0-9][0-9][0-9][0-9]//" | awk '{printf "INSERT INTO data VALUES (%s, %s, %d, %d, %d);\n", mktime($1" "$2" "$3" "$4" "$5" "$6), $34, strtonum("0x"$47$48), strtonum("0x"$49$50), strtonum("0x"$51)}' | mysql -D beerlogger &
	echo $! > $INT_PID_FILE
	
}

do_stop() {
	INT_PID=`cat $INT_PID_FILE`

	kill $INT_PID
	rm -f $INT_PID_FILE
	
	echo "Beer logger service stopped"
}

do_status() {
	if [ -e $INT_PID_FILE ]
	then
		INT_PID=`cat $INT_PID_FILE`
		
		ps -hq $INT_PID > /dev/null 
		if [[ $? -ne 0 ]]
		then
			echo "pidfile exists but process appears to be dead ($INT_PID)"
		else
			echo -n "process OK. Current count: "
			cat $COUNTERFILE
			echo ""
		fi
	else
		# no pidfile
		
		pscount=`ps aux | grep "gpio -g wfi" | wc -l`
		if [[ $pscount -gt 1 ]]
		then
			echo "No pidfile was found, however a process was found! You might want to investigate, it's probably orphaned"
			ps aux | grep "gpio -g wfi" 
		fi
	fi


}

# Main controller
# This works with systemd as well as standalone but it's not a perfect implementation. 
# In particular systemd will not pass through the status command and it doesn't really like having children
case $1 in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	status)
		do_status
		;;
	restart)
		do_stop
		sleep 2
		do_start
		;;
	*)
		echo Action \'"$@"\' is not supported.
		;;
esac

exit 0
